//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientosContables
    {
        public int IdAsiento { get; set; }
        public string Descripcion { get; set; }
        public int IdEmpleado { get; set; }
        public string Cuenta { get; set; }
        public string TipoMovimiento { get; set; }
        public System.DateTime FechaAsiento { get; set; }
        public decimal MontoAsiento { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
