//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominas
    {
        public int IdNomina { get; set; }
        public string Nombre { get; set; }
        public string TipoNomina { get; set; }
        public string Banco { get; set; }
        public System.DateTime fechaDesde { get; set; }
        public System.DateTime fechaHasta { get; set; }
        public System.DateTime FechaEfectividad { get; set; }
        public decimal Monto { get; set; }
        public Nullable<decimal> Total_AFP { get; set; }
        public Nullable<decimal> Total_ARS { get; set; }
        public Nullable<decimal> Total_ISR { get; set; }
        public Nullable<decimal> Total_ingresos { get; set; }
        public Nullable<decimal> Total_Otros_descuentos { get; set; }
        public string Observaciones { get; set; }
        public string Estado { get; set; }
    }
}
